project_id = "playground-ai-478208"
region     = "us-east1"
environment   = "global-dev"
image_tag  = "development"
artifact_image_path="us-docker.pkg.dev/playground-ai-478208/playground-global-repo/playground-backend"